import type { Metadata, Viewport } from "next";
import { Providers } from "@/components/layout/Providers";
import { AppShell } from "@/components/layout/AppShell";
import "./globals.css";

// Fonts loaded via <link> instead of next/font/google because this project
// builds with `next build --webpack` (per package.json), and next/font/google
// requires the SWC/Turbopack font loader. The CSS variables --font-display etc.
// are defined in globals.css and consumed by Tailwind config.
//
// Tracked in KNOWN-ISSUES.md — migrating to Turbopack is gated on cofhejs WASM
// support landing upstream.

const SITE_URL = "https://zerith-fi.vercel.app";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Zerith — Encrypted block sales for token foundations",
    template: "%s · Zerith",
  },
  description:
    "Sell your treasury without leaking it. Encrypted block sales for token foundations on Fhenix fully homomorphic encryption — sealed bids, fair clearing, losing prices stay encrypted forever.",
  applicationName: "Zerith",
  keywords: [
    "Zerith",
    "Fhenix",
    "FHE",
    "fully homomorphic encryption",
    "encrypted block sales",
    "token foundation treasury",
    "sealed-bid auction",
    "private DeFi",
    "MEV-resistant",
    "Ethereum",
  ],
  authors: [{ name: "Zerith" }],
  creator: "Zerith",
  publisher: "Zerith",
  alternates: {
    canonical: SITE_URL,
  },
  openGraph: {
    type: "website",
    siteName: "Zerith",
    title: "Zerith — Encrypted block sales for token foundations",
    description:
      "Sell your treasury without leaking it. Encrypted block sales for token foundations on Fhenix FHE.",
    url: SITE_URL,
    locale: "en_US",
    // Image is auto-generated by app/opengraph-image.tsx — Next.js wires it
    // into this OG block. Keeping a fallback here for robustness.
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "Zerith — Encrypted block sales for token foundations on Fhenix FHE",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Zerith — Encrypted block sales for token foundations",
    description:
      "Sell your treasury without leaking it. Sealed bids, fair clearing, losing prices stay encrypted forever.",
    creator: "@zerithfi",
    site: "@zerithfi",
    images: ["/opengraph-image"],
  },
  // Favicons: Next.js auto-detects app/icon.tsx and app/apple-icon.tsx and
  // injects them. Listing /favicon.svg explicitly here so browsers that
  // support SVG favicons (Chrome, Firefox, modern Edge) prefer it. Safari
  // on iOS / older Safari falls back to the PNG generated by icon.tsx.
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/icon", sizes: "32x32", type: "image/png" },
    ],
    shortcut: ["/favicon.svg"],
    apple: [{ url: "/apple-icon", sizes: "180x180", type: "image/png" }],
  },
  category: "finance",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FAFAF7" },
    { media: "(prefers-color-scheme: dark)", color: "#FAFAF7" },
  ],
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=JetBrains+Mono:wght@400;500;700&family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>
      </body>
    </html>
  );
}
